$("body").css("background-image", "url" ("background2.png"));
$("body").css("background-repeat", "no-repeat")
$("body").css("background-size", "cover")
$(".logo").css("position", "absolute")
$(".logo").css("top", "20%")
$(".logo").css("left", "54%")
$(".logo").css("border", "none")
$(".logo").css("color", "#795548");
$(".logo").css("text-align", "center")
$(".logo").css("text-decoration", "none")
$(".logo").css("display", "inline-block")
$(".logo").css("curson", "pointer")
$(".logo").css("transition-duration", "0.4s")
$(".logo").css("background-color", "#795548")
$(".logo").css(" color", "black")
$(".quote1").css("fontFamily", 'Jim Nightshade', "cursive")
$(".quote2").css("fontFamily", 'Jim Nightshade', "cursive")
$(".quote3").css("fontFamily", 'Jim Nightshade', "cursive")
$(".quote4").css("fontFamily", 'Jim Nightshade', "cursive")
$(".quote5").css("fontFamily", 'Jim Nightshade', "cursive")
$(".if").css("fontFamily", 'Jim Nightshade', "cursive")